### PR TITLE
Adding my name to the participant list

### PR DESCRIPTION
**Pull request by pauljacobson**
Let's see if this works

### CODE REVIEW

**Comment by pauljacobson** [comment]
@szabgab How would we resolve this merge conflict?

**Comment by szabgab** [comment]
Assuming you made the changes in a branch, you can update the main (or master) branch from upstream. Then you can switch to your branch, rebase it onto main (or master). During the rebase it will probably complain about the conflict. Then you have a chance to edit the file and fix the complain. Then you can run `git rebase --continue`

Then you can push out the updated branch. You will probably need to use the force for that. `git push --force` as this push replaces the one you already have in GitHub.

Let me know if you'd like to try it.

**Comment by szabgab** [comment]
Look for "conflict" in the collab book.

**Comment by pauljacobson** [comment]
Got it, ok, I'll attempt this a little later today. Thanks!

**Comment by pauljacobson** [comment]
When I try to update my repo from the upstream repo using `git pull upstream main`, I get this error:

```
From https://github.com/szabgab/codeandtalk.com
 * branch              main       -> FETCH_HEAD
fatal: refusing to merge unrelated histories
```

**Comment by szabgab** [comment]
Have you checked out the main branch?

```
git checkout main
git pull upstream main
```
please paste the output of `git remote -v`

**Comment by pauljacobson** [comment]
Yes, I did. Here is the output:

```
origin	git@github.com:pauljacobson/modiin-co-learning.git (fetch)
origin	git@github.com:pauljacobson/modiin-co-learning.git (push)
upstream	https://github.com/szabgab/codeandtalk.com.git (fetch)
upstream	https://github.com/szabgab/codeandtalk.com.git (push)
```

**Comment by szabgab** [comment]
Look closer. The origin is based on the modiin-co-learning repository. The upstream is connected to a codeandtalk repo. There is some mixup.

**Comment by pauljacobson** [comment]
Ah, I missed that. I've fixed that and merged the conflict in my repo. How do I update the upstream repo?

**Comment by szabgab** [comment]
You can't update the upstream repo. You don't have rights there. You can update your local repo from upstream 
```
git checkout main
git pull upstream main
```
then you can update the main of your origin repo from your local repo:
```
git push
```
 and you can also rebase your branch onto main:
```
git checkout your-branch
git rebase main
```

**Comment by pauljacobson** [comment]
Hi

Ok, so the idea is to create a branch in my repo, make the changes, and then merge those changes back into my main branch after updating it from the upstream repo?

**Comment by szabgab** [comment]
No. You are not supposed to merge the branch back. You are supposed to rebase the branch. I guess I'll need to update the book with clearer explanation.

**Comment by pauljacobson** [comment]
@szabgab I'll read through it again before you did. It's very possible I missed something.

**Pull request merged**
